#2. Write a program to input eight numbers from the user and display all the unique
#numbers (once).
s = set()
n = input('enter number n1:')
s.add(int(n))
n = input('enter number n2:')
s.add(int(n))
n = input('enter number n3:')
s.add(int(n))
n = input('enter number n4:')
s.add(int(n))
n = input('enter number n5:')
s.add(int(n))
n = input('enter number n6:')
s.add(int(n))
n = input('enter number n7:')
s.add(int(n))
n = input('enter number n8:')
s.add(int(n))
print('the unique set is : ' ,s)
